name: az_eus
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - anyio=4.6.2=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=24.2.0=py312h06a4308_0
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_1
  - blas=1.0=openblas
  - bleach=6.2.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - cpython=3.12.11=py312hd8ed1ab_0
  - cuda-cccl_linux-64=12.6.77=ha770c72_0
  - cuda-crt-dev_linux-64=12.6.85=ha770c72_0
  - cuda-crt-tools=12.6.85=ha770c72_0
  - cuda-cudart=12.6.77=h5888daf_0
  - cuda-cudart-dev=12.6.77=h5888daf_0
  - cuda-cudart-dev_linux-64=12.6.77=h3f2d84a_0
  - cuda-cudart-static=12.6.77=h5888daf_0
  - cuda-cudart-static_linux-64=12.6.77=h3f2d84a_0
  - cuda-cudart_linux-64=12.6.77=h3f2d84a_0
  - cuda-cupti=12.6.80=hbd13f7d_0
  - cuda-cupti-dev=12.6.80=h5888daf_0
  - cuda-driver-dev_linux-64=12.6.77=h3f2d84a_0
  - cuda-nvcc=12.6.85=hcdd1206_0
  - cuda-nvcc-dev_linux-64=12.6.85=he91c749_0
  - cuda-nvcc-impl=12.6.85=h85509e4_0
  - cuda-nvcc-tools=12.6.85=he02047a_0
  - cuda-nvcc_linux-64=12.6.85=h04802cd_0
  - cuda-nvrtc=12.6.85=hbd13f7d_0
  - cuda-nvtx=12.6.77=hbd13f7d_0
  - cuda-nvvm-dev_linux-64=12.6.85=ha770c72_0
  - cuda-nvvm-impl=12.6.85=he02047a_0
  - cuda-nvvm-tools=12.6.85=he02047a_0
  - cuda-version=12.6=h7480c83_3
  - cudnn=9.3.0.75=h3e9b439_1
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.4.0=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - gcc_impl_linux-64=13.3.0=hfea6d02_1
  - gcc_linux-64=13.3.0=hc28eda2_7
  - gxx_impl_linux-64=13.3.0=hdbfa832_1
  - gxx_linux-64=13.3.0=h6834431_7
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.28.0=pyhd8ed1ab_1
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=py312h06a4308_0
  - ipykernel=6.29.5=py312h06a4308_0
  - ipython=8.27.0=py312h06a4308_0
  - jaxlib=0.4.34=cuda126py312hb76f226_201
  - jedi=0.19.1=py312h06a4308_0
  - jinja2=3.1.4=py312h06a4308_1
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.3.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20240722.0=cxx17_h5888daf_1
  - libblas=3.9.0=26_linux64_openblas
  - libcblas=3.9.0=26_linux64_openblas
  - libcublas=12.6.4.1=hbd13f7d_0
  - libcublas-dev=12.6.4.1=h5888daf_0
  - libcufft=11.3.0.4=hbd13f7d_0
  - libcufft-dev=11.3.0.4=h5888daf_0
  - libcurand=10.3.7.77=hbd13f7d_0
  - libcurand-dev=10.3.7.77=h5888daf_0
  - libcusolver=11.7.1.2=hbd13f7d_0
  - libcusolver-dev=11.7.1.2=h5888daf_0
  - libcusparse=12.5.4.2=hbd13f7d_0
  - libcusparse-dev=12.5.4.2=h5888daf_0
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=13.3.0=h84ea5a7_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.65.5=hf5c653b_0
  - liblapack=3.9.0=26_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.6.85=hbd13f7d_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libprotobuf=5.27.5=h5b01275_2
  - libre2-11=2024.07.02=hbbce691_1
  - libsanitizer=13.3.0=heb74ff8_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=13.3.0=h84ea5a7_101
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - ml_dtypes=0.5.0=py312h6a678d5_0
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.16.4=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - nccl=2.23.4.1=h2b5d15b_3
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - notebook-shim=0.2.3=py312h06a4308_0
  - numpy=2.1.3=py312h58c1407_0
  - openssl=3.5.2=h26f9b46_0
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.1=py312h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pbr=7.0.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - prometheus_client=0.21.0=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - qiskit=2.1.2=py310h1570de5_1
  - re2=2024.07.02=h77b4e00_1
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.3=py312h06a4308_1
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.10.6=py312h4aa5aa6_1
  - rustworkx=0.17.1=py310h1570de5_3
  - scipy=1.14.1=py312h2809609_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=75.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stevedore=5.5.0=pyhd8ed1ab_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py312h06a4308_1
  - tornado=6.4.1=py312h5eee18b_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - absl-py==2.1.0
      - arrow==1.3.0
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - chex==0.1.87
      - click==8.1.7
      - cssselect2==0.7.0
      - dm-haiku==0.0.12
      - docker-pycreds==0.4.0
      - etils==1.11.0
      - flax==0.8.5
      - fqdn==1.5.1
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - graphviz==0.20.3
      - humanize==4.11.0
      - importlib-resources==6.4.5
      - isoduration==20.11.0
      - jax==0.4.35
      - jax-cuda12-pjrt==0.4.35
      - jax-cuda12-plugin==0.4.35
      - jmp==0.0.4
      - jsonpointer==3.0.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - msgpack==1.1.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.6.85
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.0.50
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.6.85
      - optax==0.1.9
      - orbax==0.1.9
      - orbax-checkpoint==0.10.2
      - pgx==2.5.0
      - pillow==11.0.0
      - protobuf==5.29.1
      - qujax==1.1.0
      - rich==13.9.4
      - sentry-sdk==2.19.0
      - setproctitle==1.3.4
      - simplejson==3.19.3
      - smmap==5.0.1
      - svgwrite==1.4.3
      - tabulate==0.9.0
      - tensorstore==0.1.69
      - toolz==1.0.0
      - types-python-dateutil==2.9.0.20241003
      - uri-template==1.3.0
      - wandb==0.18.7
      - webcolors==24.11.1
